### ISSUE TITLE
Menu displays no info when "a" selector is used

### ISSUE THREAD

**Issue by axl89** [anseki/jquery-contextmenu-common#2]
In this HTML
```
<ul class="data animated">
	<li class="folders"><a href="/test_inside" title="/test_inside" class="folders"><span class="icon folder full"></span><span class="name">test_inside</span> <span class="details">1 item</span></a></li>
	<li class="folders"><a href="/pills" title="/pills" class="folders"><span class="icon folder"></span><span class="name">pills</span> <span class="details">Empty</span></a></li>
	<li class="folders"><a href="/dir" title="/dir" class="folders"><span class="icon folder"></span><span class="name">dir</span> <span class="details">Empty</span></a></li>
</ul>
```

And using this selector

```
$.contextMenuCommon({
		  selector: '.data li a',
		  items: {

		   fontBold: {
		      label: 'Bold Font',
		      type: 'checkbox'
		    },

		    fontSize: {
		      label: 'Font Size',
		      items: {
		        size1: {
		          label: 'Small',
		          type: 'radio'
		        },
		        size2: {
		          label: 'Medium',
		          type: 'radio'
		        },
		        size3: {
		          label: 'Large',
		          type: 'radio'
		        }
		      }
		    }

		  }
		});
```

I get no display at all of the menu:
![Screencap](https://dl.dropboxusercontent.com/u/374770/github/plugin.JPG)

I don't if I'm able to provide all the details, but I'm using:
* jquery 2.0.3
* jQuery UI - v1.11.4

If I change the selector to `selector: '.data'` **it works**, but unfortunately I need to be able to make different selectors on different classes.

**Comment by axl89** [comment]
I've been able to fix this by putting the selector code within a _render_ function that was called after all the data was added to the `data` div 👍

**Comment by anseki** [comment]
Hi @axl89,
I tried your example code, and that worked fine perfectly.
https://jsfiddle.net/ujppwvsL/
![ss](https://cloud.githubusercontent.com/assets/4763469/20484062/bda0d1c2-b038-11e6-954a-c234032ceb55.png)
Therefore, your another JavaScript code or CSS code seems to have problem. The your code might hide the text (style property), or it might change DOM elements of the menu.
Check your code, for example, disable your code as an experiment.
